"project_id" : "2"
"base_path" : "."
"base_url" : "https://berty.crowdin.com"

"commit_message": 'fix(i18n): new %language% translations


Signed-off-by: Crowdin Bot <bot@crowdin.com>'

"append_commit_message": false
"preserve_hierarchy": true

files: [
 {
  "source" : "/js/packages/berty-i18n/locale/en/messages.json",
  "translation" : "/js/packages/berty-i18n/locale/%two_letters_code%/%original_file_name%",
 },
 {
  "source" : "/go/internal/i18n/locales/en.json,
  "translation" : "/go/internal/i18n/locales/%two_letters_code%.json",
 }
]
